ci(version-check): prevents deploys from ci, docs or non lib code

diff --git a/.github/workflows/version-check.yml b/.github/workflows/version-check.yml
--- a/.github/workflows/version-check.yml
+++ b/.github/workflows/version-check.yml
@@ -64,6 +64,12 @@ jobs:
             exit 0
           fi
 
+          # If NEXT_VERSION is empty, fail the workflow
+          if [[ -z "$NEXT_VERSION" ]]; then
+            echo "❌ No new version detected. Exiting with failure."
+            exit 1
+          fi
+
           # Remove "v" prefix if it exists
           LAST_VERSION=${LAST_VERSION#v}
           NEXT_VERSION=${NEXT_VERSION#v}
